export interface SaleRecord {
  id: string;
  date: string; // YYYY-MM-DD
  revenue: number;
  transactions: number;
  topProduct: string;
  notes: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: number;
}

export interface NavItem {
  label: string;
  path: string;
  icon: React.ComponentType<any>;
}

export type ViewState = 'landing' | 'dashboard';

// --- New Features Types ---

export type ThemeOption = 'dark' | 'light' | 'cyber' | 'pastel';
export type LayoutOption = 'simple' | 'analytic' | 'compact' | 'modern';
export type AnalyticsMode = 'basic' | 'advanced' | 'forecast';

export interface AppSettings {
  theme: ThemeOption;
  layout: LayoutOption;
  analyticsMode: AnalyticsMode;
  enableDummyData: boolean;
}

export interface SalesGoal {
  month: string; // YYYY-MM
  targetAmount: number;
  notes?: string;
}

export interface DailyTask {
  id: string;
  text: string;
  isCompleted: boolean;
  date: string; // YYYY-MM-DD
  generatedAt: number;
}

export interface StoreProfile {
  ownerName: string;
  storeName: string;
}

export interface ExpenseRecord {
  id: string;
  date: string;
  description: string;
  amount: number;
  category: string; // 'Operasional', 'Stok', 'Marketing', etc. (Auto-generated by AI)
}

export interface InventoryRecord {
  id: string;
  period: string; // YYYY-MM
  cogs: number; // Cost of Goods Sold
  avgInventory: number; // (Beginning + Ending) / 2
  turnoverRate: number;
  aiInsight?: string;
}